project:
  output-dir: docs
  type: website
  render: 
    - www/TAC_chinook_figures.qmd
    - www/TAC_steelhead_figures.qmd
    - www/about.qmd

website:
  title: "Track-a-Cohort"
  search: true
  navbar:
    left:
      - href: www/TAC_chinook_figures.qmd
        text:  Winter-run
      - href: www/TAC_steelhead_figures.qmd
        text:  Steelhead
      - href: www/about.qmd
        text: About



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  # pdf:
  #   toc: false

editor: visual

