#'import STARS data from ShinyApp
#'@description This script imports up to date STARS data from the ShinyApp and saves it to the data folder for use in other scripts. Code provided by Nick Beer.
#'@return STARS_data.rda saved to `data` folder
require(tidyverse)
require(usethis)
require(here)
require(xts)
require(zoo)


#load STARS data
# url of .Rdata file generated by SI for STARS ShinyApp on SacPAS server
url <- "https://www.cbr.washington.edu/sacramento/cohort/include_wrc/STARS.shinyinputs.Rdata"
# make url connection live
source <-url(url)
# load live url 
load(source)
#close url connection
close(source)

#load hydrological classification index
source(here::here("data-raw/utils_import_hydrological_classification_index.R"))


# Subset the data and convert to tibble
df_stars_raw <- tibble::as_tibble(WR_xts[,c("Survival Interior Delta Est", 
                                    "Survival Interior Delta LCL 80", 
                                    "Survival Interior Delta UCL 80",
                                    "Routing Probability Interior Delta Est",    
                                    "Routing Probability Interior Delta LCL 80",
                                    "Routing Probability Interior Delta UCL 80",
                                    "Survival Overall Est", 
                                    "Survival Overall LCL 80",
                                    "Survival Overall UCL 80")]) %>%
  # Add the first date as a new column
  mutate(date = zoo::index(WR_xts)) %>%
  # Make date the first column
  select(date, everything()) %>%
  rename( surv =  "Survival Overall Est", survL80 =  "Survival Overall LCL 80", survU80 =  "Survival Overall UCL 80", 
          idsurv = "Survival Interior Delta Est", idsurvL80 = "Survival Interior Delta LCL 80", idsurvU80 = "Survival Interior Delta UCL 80", 
          idRoute = "Routing Probability Interior Delta Est", idRouteL80 =  "Routing Probability Interior Delta LCL 80", idRouteU80 =  "Routing Probability Interior Delta UCL 80") %>%
  # convert date to WY, wday
  arrange(date) %>% 
  mutate(WY = year(date) + (month(date) >= 10),
         wDay = if_else(month(date) >= 10, yday(date) - 273, yday(date) + 92),
         doy = yday(date),
         CY = year(date),
         wDate = if_else(month(date) >= 10, date + years(1), date)) 

#based in NB feedback, the model only forecasts through 7/31 and then no fish are running therefore forecast returns 0, filter dates beyond 7/31 in the CY to only show WY: 10-01 to 07-31
filtered_dates <- df_stars_raw %>%
  filter(!(year(wDate) == CY & (month(wDate) > 7 | (month(wDate) == 7 & day(wDate) > 31))))

# append HCI classification to STARS data (for shiny app)
STARS_data <- filtered_dates %>%
  dplyr::left_join(select(hydrological_classification_index, WY, hydro_type = Classification), by = "WY") %>%
  dplyr::mutate(hydro_type = factor(
    ifelse(is.na(hydro_type), "Unassigned", hydro_type),
    levels = c("Wet", "Above Normal", "Below Normal", "Dry", "Critical", "Unassigned")
  )
  ) 
  


#save to data folder for use in other scripts
usethis::use_data(STARS_data, overwrite = TRUE)
