#load_dependencies.R
library(gghighlight)
library(ggplot2)
library(ggrepel)
library(ggridges)
library(here)
library(janitor)
library(knitr)
library(kableExtra)
library(lubridate)
library(patchwork)
library(readr)
library(scales)
library(tidyverse) #if in package form pull out specific libraries -- dplyr, ggplot2, tidyr, lubridate, etc
library(usethis) 
library(xts)
library(zoo)